---
# it is suggested that these be encrypted with ansible-vault:
# ansible-vault edit /etc/ansible/group_vars/windows.yml
#
# using old style names for compatibility with Ansible versions < 2.0

ansible_ssh_user: Administrator
ansible_ssh_password: {{admin_user_password}}
ansible_ssh_port: 5986
ansible_connection: winrm

# The following is necessary for Python 2.7.9+ when using default WinRM self-signed certificates:
ansible_winrm_server_cert_validation: ignore
