#!/bin/sh -ex
# main installation script

# pip install PyYAML jinja2 paramiko

# install ansible
cd /opt
git clone https://github.com/ansible/ansible.git
cd ansible

git checkout $( git tag | tail -1 )

make install

