#!/bin/bash -ex

# install pip
easy_install pip

# upgrade setuptools
python -m pip install --upgrade --force setuptools

# install ansible
pip install 'ansible==2.3.1.0'

# install Windows support
pip install --upgrade 'pywinrm>=0.1.1'

ANSIBLE_USER=ansible
ANSIBLE_PASS=turnkey

# create admins group with sudo privileges
addgroup --system admins

# create ansible user with default password
adduser --disabled-login --gecos 'ansible user' $ANSIBLE_USER
echo $ANSIBLE_USER:$ANSIBLE_PASS | chpasswd

# give ansible user sudo privileges
usermod -a -G admins $ANSIBLE_USER

# create ansible log directory
mkdir -p /var/log/ansible
chown ansible:ansible /var/log/ansible

# add keychain to ~/.bashrc.d
cat << _EOF_ > /home/$ANSIBLE_USER/.bashrc.d/keychain
keychain ~/.ssh/id_rsa
source ~/.keychain/$HOSTNAME-sh
_EOF_
chmod 0755 /home/$ANSIBLE_USER/.bashrc.d/keychain

HTDOCS=/var/www/ansible/htdocs

# webserver related
mkdir -p $HTDOCS/{css,images}
cp /var/www/js/ui.* $HTDOCS/js/
cp /var/www/css/*.css $HTDOCS/css/
cp /var/www/images/{webmin.png,shell.png,tab.png} $HTDOCS/images/
rm -rf /var/www/{js,css,images}

# ansible lighty.conf overlay includes ssl
lighttpd-disable-mod ssl

# git clone ansible-examples
su ansible -c "git clone https://github.com/ansible/ansible-examples.git /home/ansible/examples" 
