#!/bin/bash -ex

# install setuptools
python -m pip install --upgrade --force setuptools

# upgrade pip
python -m pip install --upgrade --force pip

# install ansible
pip install --upgrade 'ansible==2.2.0.0'

# install Windows support
pip install --upgrade 'pywinrm>=0.1.1'

# install ansible-lxc-ssh
mkdir -p /usr/share/ansible_plugins/connection_plugins
curl -sS --tlsv1.2 -o /usr/share/ansible_plugins/connection_plugins/lxc_ssh.py https://raw.githubusercontent.com/Dude4Linux/ansible-lxc-ssh/master/lxc_ssh.py

ANSIBLE_USER=ansible
ANSIBLE_PASS=turnkey

# create admins group with sudo privileges
addgroup --system admins

# create ansible user with default password
adduser --disabled-login --gecos 'ansible user' $ANSIBLE_USER
echo $ANSIBLE_USER:$ANSIBLE_PASS | chpasswd

# give ansible user sudo privileges
usermod -a -G admins $ANSIBLE_USER

# add keychain to ~/.bashrc.d
cat << _EOF_ > /home/$ANSIBLE_USER/.bashrc.d/keychain
keychain ~/.ssh/id_rsa
source ~/.keychain/$HOSTNAME-sh
_EOF_
chmod 0755 /home/$ANSIBLE_USER/.bashrc.d/keychain

HTDOCS=/var/www/ansible/htdocs

# webserver related
mkdir -p $HTDOCS/{css,images}
cp /var/www/js/ui.* $HTDOCS/js/
cp /var/www/css/*.css $HTDOCS/css/
cp /var/www/images/{webmin.png,shell.png,tab.png} $HTDOCS/images/
rm -rf /var/www/{js,css,images}

# ansible lighty.conf overlay includes ssl
lighttpd-disable-mod ssl

# git clone ansible-examples
su ansible -c "git clone https://github.com/ansible/ansible-examples.git /home/ansible/examples" 
