#!/bin/bash -e
# setup ansible password & ssh key

APP_USER=ansible

. /etc/default/inithooks

[ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF

$INITHOOKS_PATH/bin/setpass_key.py $APP_USER --pass="$APP_PASS"

