#!/bin/bash -e
# add ansible ssh key to root's authorized_keys
# allows ansible to login as root without a password

APP_USER=ansible

. /etc/default/inithooks

[ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF

# make sure the .ssh directory exists
if [[ $SUDOADMIN == "true" ]]; then
    ADMIN_HOME=/home/admin
else
    ADMIN_HOME=/root
fi
mkdir -p $ADMIN_HOME/.ssh
cat /home/$APP_USER/.ssh/id_rsa.pub >> $ADMIN_HOME/.ssh/authorized_keys
