#!/bin/bash -e
# add ansible ssh key to root's authorized_keys
# allows ansible to login as root without a password

APP_USER=ansible

. /etc/default/inithooks

[ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF

# make sure the .ssh directory exists
mkdir -p /root/.ssh
cat /home/$APP_USER/.ssh/id_rsa.pub >> /root/.ssh/authorized_keys
