---

# playbooks/init.yml
#
# This playbook prepares a host to be managed by ansible using the root
# account. You should run it just after new server has been installed and
# connected to the network. Make sure that you can access the root account
# through ssh. You might have to provide a password (in that case use '-k'
# switch on the command line to prompt for the password).
#
# Usage:
# ansible-playbook -k playbooks/init.yml -l "<hostname>"
#

- hosts: all
  remote_user: root
  sudo: no
  gather_facts: False
  tags: init
  vars:
    ssh_user: '{{lookup("env", "USER")}}'
    ssh_key: '{{lookup("file", "~/.ssh/id_rsa.pub")}}'

  tasks:
  - name: INIT | Install python support for Ansible
    raw: apt-get -yq install python python-apt
    tags: init

  - action: setup
    tags: init

  - name: INIT | Make sure essential software is installed
    apt:
      name: '{{item}}'
      state: 'latest'
      install_recommends: False
    with_items:
      - python
      - python-apt
      - lsb-release
    tags: init

  - name: INIT | Install ssh public key from current account
    authorized_key:
      user: '{{ssh_user}}'
      key: '{{ssh_key}}'
      state: 'present'
    failed_when: (ssh_key is undefined or (ssh_key is defined and not ssh_key))
    tags: init
